development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: fellows_development
  pool: 5
  username: ivan_pg
  password: 123456

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: fellows_text
  pool: 5
  username: ivan_pg
  password: 123456

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: fellows_production
  pool: 5
  username: ivan_pg
  password: 123456
